
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.tsx", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    screens: {
      xs: "0px",    
      sm: "480px",  
      md: "768px",   
      lg: "1024px",  
      xl: "1280px",  
    },
    extend: {
      colors: {
        brand: {
          bg:           "#0C1422",
          bgCard:       "#131D2E",
          bgInput:      "#F0F2F5",
          bgElevated:   "#1C2A42",
          primary:      "#6B21A8",
          primaryLight: "#7C3AED",
          accent:       "#A855F7",
          border:       "rgba(243,237,229,0.1)",
          borderLight:  "rgba(243,237,229,0.1)",
          divider:      "rgba(243,237,229,0.07)",
          textPrimary:  "#F3EDE5",
          textSecondary:"rgba(243,237,229,0.5)",
          textSub:      "rgba(243,237,229,0.5)",
          textMuted:    "rgba(243,237,229,0.5)",
          textLabel:    "#CBD5E1",
          textInput:    "#0F172A",
          textPlaceholder: "#94A3B8",
          btnBg:        "#0F172A",
          btnBorder:    "#334155",
          google:       "#1E293B",
          iconStroke:   "#64748B",
          iconActive:   "#A855F7",
          white:        "#FFFFFF",
          gold:         "#D4A84B",
          goldLight:    "#E8D5A3",
          tabActive:    "#4A82D8",
          tabInactive:  "rgba(243,237,229,0.4)",
          bgMain:       "#0C1422",
          bgCardMain:   "#121A2B",
          bgCardSoft:   "#1A2840",
          borderSoft:   "rgba(243,237,229,0.07)",
          blueSoft:     "#7AB0F5",
          purpleSoft:   "#A78BFA",
        },
      },
      fontFamily: {
        heading:       ["CormorantGaramond-Bold",     "serif"],
        headingSemi:   ["CormorantGaramond-SemiBold", "serif"],
        headingMedium: ["CormorantGaramond-Medium",   "serif"],
        headingRegular:["CormorantGaramond-Regular",  "serif"],
        headingItalic: ["CormorantGaramond-Italic",   "serif"],
        sans:          ["DMSans-Regular",  "sans-serif"],
        sansMedium:    ["DMSans-Medium",   "sans-serif"],
        sansSemiBold:  ["DMSans-SemiBold", "sans-serif"],
        sansBold:      ["DMSans-Bold",     "sans-serif"],
        sansItalic:    ["DMSans-Italic",   "sans-serif"],
        label:         ["DMSans-Medium",   "sans-serif"],
      },
      borderRadius: {
        card:  "20px",
        input: "10px",
        btn:   "14px",
        icon:  "18px",
      },
      fontSize: {
        "display-xl": ["32px", { lineHeight: "38px", letterSpacing: "0.2px" }],
        "display-lg": ["28px", { lineHeight: "34px", letterSpacing: "0.2px" }],
        "heading-md": ["22px", { lineHeight: "28px" }],
        "body-lg":    ["16px", { lineHeight: "24px" }],
        "body-md":    ["14px", { lineHeight: "20px" }],
        "body-sm":    ["13px", { lineHeight: "18px" }],
        label:        ["13px", { lineHeight: "16px", letterSpacing: "0.3px" }],
        caption:      ["11px", { lineHeight: "14px", letterSpacing: "1.6px" }],
      },
      spacing: {
        card:    "24px",
        section: "32px",
      },
      boxShadow: {
        card:  "0 8px 24px rgba(0,0,0,0.5)",
        input: "0 1px 3px rgba(0,0,0,0.12)",

  
        'glow-blue':    "0 0 20px 4px rgba(74,130,216,0.45)",
        'glow-blue-lg': "0 0 28px 8px rgba(74,130,216,0.55)",
        'glow-gold':    "0 0 20px 4px rgba(212,168,75,0.45)",
        'glow-gold-lg': "0 0 28px 8px rgba(212,168,75,0.55)",
        'glow-green':   "0 0 18px 4px rgba(94,201,126,0.4)",
      },
    },
  },
  plugins: [],
};